# Generated by Django 4.2 on 2025-06-25 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_borrow_date_tool_borrowed_by_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
